### PR TITLE
Update pico-sdk to latest version 1.3.0

### PR DESCRIPTION
**Pull request by giulcioffi**
### Summary of changes 

For pico-sdk updates, refer to https://github.com/raspberrypi/pico-sdk/releases/tag/1.3.0 .

The PR introduces also one additional fix about `hal_watchdog_get_reload_value()`, which was not returning the timeout value in milliseconds, as specified in the declaration: https://github.com/arduino/mbed-os/blob/6959b7db85d808b747949b528289eb9220eae0d5/drivers/include/drivers/Watchdog.h#L117-L123 .

#### Impact of changes 

This PR will solve the following issues:
- https://github.com/arduino/ArduinoCore-mbed/issues/250
- https://github.com/arduino/ArduinoCore-mbed/issues/243
- https://github.com/arduino/ArduinoCore-mbed/issues/217
- https://github.com/arduino/ArduinoCore-mbed/issues/279
- https://github.com/arduino/ArduinoCore-mbed/issues/288
- https://github.com/arduino/ArduinoCore-mbed/issues/300
- https://github.com/arduino/ArduinoCore-mbed/issues/367
- https://github.com/arduino/ArduinoCore-mbed/issues/461

### Documentation 

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [x] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [x] Tests / results supplied as part of this PR

Nano RP2040 CONNECT successful tests:
- UART        
- I2C
- us_ticker
- lp_ticker
- RTC
- watchdog
- PDM
- ADC
- flash
- interrupt
- PWM
- dma

Raspberry Pi Pico successful tests:
- UART        
- I2C
- us_ticker
- lp_ticker
- RTC
- watchdog
- ADC
- flash
- interrupt
- PWM
- dma
----------------------------------------------------------------------------------------------------------------
### Reviewers 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @giulcioffi :coffee: :wave:

I've tested a ArduinoCore-mbed built with this PR with the Braccio++ with
* [Braccio_Record_and_Replay](https://github.com/arduino-libraries/Arduino_Braccio_plusplus/tree/main/examples/Braccio_Record_and_Replay) :heavy_check_mark: 
* [Controlling_Manually_Braccio](https://github.com/arduino-libraries/Arduino_Braccio_plusplus/tree/main/examples/Controlling_Manually_Braccio) :heavy_check_mark: 

and both work fine.

The important part for the Braccio++'s RS485 communication that this [change](https://github.com/arduino/mbed-os/commit/f0b1b6c7375568f3256d09287956dc0649b46b20) is preserved which you've done.

**Comment by facchinm** [comment]
Everything looks good but I'd split the patches over 1.3.0 in probably 3 or 4, namely:
* prepend `_` to clashing functions names
* change standard interrupt names and linker script to be CMSIS compliant
* i2c read() modification to make it compliant with mbed APIs
* change uart is_writable() logic to handle FIFO

**Comment by giulcioffi** [comment]
Done :) now the commits should be divided in a better way.

**Review by facchinm — APPROVED** [review]

**Comment by aentinger** [comment]
Tested an ArduinoCore-mbed built with this changes and one Braccio++ example, all is fine :+1: :heavy_check_mark:

**Pull request merged**
