### PR TITLE
STM32H7: USE_SD_TRANSCEIVER is configurable

### PR DESCRIPTION
**Pull request by pennam**
### Summary of changes 
This pull request allow configuration of USE_SD_TRANSCEIVER using targets.json file

            "sd_transceiver_available": {
                "help": "Define if SD transceiver is available on the board.",
                "value": true
            }

Default value for STM32H7 targets is 1but can be changed using override section of a specific target.

            "overrides": {
                "sd_transceiver_available": false
            },

#### Impact of changes 
STM32H7 family

### Documentation 

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [X] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 
@facchinm

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by pennam** [comment]
@facchinm i've aligned this branch to this https://github.com/arduino/mbed-os/tree/config_sd_transceiver so you can have a look at the changes. If you agree i will then close this and open a pull request to ARMmbed/mbed-os.

**Comment by facchinm** [comment]
I think this one can be opened on mbed-os as is :wink: 
Thx

**Comment by pennam** [comment]
Rebased and mainlined as #14145

**Comment by pennam** [comment]
Closing because #14145 has been merged

**Pull request closed without merging**
