### PR TITLE
PORTENTA_H7: CYW4343X support and BLE low power implementation

### PR DESCRIPTION
**Pull request by pennam**
### Summary of changes 
1) COMPONENT_CYW4343X make transport layer generic.
2) BLE low power implementation for PORTENTA board. 

#### Impact of changes 
All boards using COMPONENT_CYW4343X

### Documentation 

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [X] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by pennam** [comment]
This PR should be applied after #8 because of "4343W", "CYW43XXX" components

**Comment by pennam** [comment]
@facchinm @Polldo i need some advice about https://github.com/arduino/mbed-os/commit/3a385561a4e0024968134041668d3e2b46d1c94f and https://github.com/arduino/mbed-os/commit/cca40435294682c64b6932a6851f4fd9fb115f99. They are not needed anymore?

**Comment by facchinm** [comment]
So, we need to retest on nano33ble, but cca4043 should be dropped (it's harmful in the latest versions of Cordio).
3a38556 is a bit more complicated since it is needed by some v3 boards (which are actively being sold). It's not needed for sure on v4, so I'd keep in out "extrapatches" when building the core but avoid filing it mainline.

**Comment by pennam** [comment]
On my v3 board https://github.com/arduino/mbed-os/commit/3a385561a4e0024968134041668d3e2b46d1c94f is not needed but without https://github.com/arduino/mbed-os/commit/6378d88e906e2da4e74cd5220eed7b04ccc5ea61 BLE is not working.
For portenta boards i would keep this pr as is plus  https://github.com/arduino/mbed-os/commit/3a385561a4e0024968134041668d3e2b46d1c94f and https://github.com/arduino/mbed-os/commit/6378d88e906e2da4e74cd5220eed7b04ccc5ea61 as BLE "extrapatches"

**Comment by pennam** [comment]
@facchinm i was submitting the pr but then i tought that cypress would not be happy to lose cyhal support, so i've made some changes here https://github.com/pennam/mbed-os/commit/2db301c7ed5906010a1f950c87859eae609c66b9. What d you think abot it? It is not beautiful to see but it will preserve cyhal support for cypress targets and the possibility to use uart for all the others.

**Comment by pennam** [comment]
Mainlined as #14227 and #14420

**Pull request closed without merging**
